[project]
name = "simple-agent-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "tinker>=0.2.2",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
